### PR TITLE
Add tag checkout before install for stability

### PR DESCRIPTION
**Pull request by tedmiston**

### CODE REVIEW

**Comment by schnie** [comment]
Should we template the version in somehow or just indicate that it's a variable, rather than just putting 0.3.1 in there? Don't want to have to update this every release, ya know?

**Comment by tedmiston** [comment]
Template would be great if possible.  I don't know if we have a feature like includes in this markdown to html generator.

I could also change it to just say `<latest tag>`?

**Comment by schnie** [comment]
Yea `<latest tag>` should be good enough.

**Comment by tedmiston** [comment]
@schnie Updated - feel free to merge if it looks good.

**Pull request merged**
